name: build

on:
  push:
    branches:
      - main
      - '*'
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '5 0 1 * *'
  workflow_dispatch:
    
env:
  IMAGE_NAME: crontab
  GITHUB_REGISTRY: ghcr.io

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - if: github.ref == 'refs/heads/main'
        name: Conditional(Set tag as `latest`)
        run: echo "tag=${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags/')
        name: Conditional(Set tag as `{version}`)
        run: |
          echo "tag=${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/heads/')
        name: Conditional(Set tag as `{version}`)
        run: |
          echo "tag=${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.tag }}
